# Generated by Django 4.1.3 on 2022-12-26 08:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('parent_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('has_next_reply_cmt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetailProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_IMEI', models.CharField(max_length=24, unique=True)),
                ('start_guarantee', models.DateField()),
                ('end_guarantee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageID', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('detail', models.ManyToManyField(to='API.detailproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.BigIntegerField()),
                ('bonus', models.BigIntegerField(default=0)),
                ('allowance', models.BigIntegerField(default=1500000)),
                ('overtime', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=28, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('fullName', models.CharField(max_length=128, null=True)),
                ('address', models.CharField(max_length=1080)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('avatar', models.CharField(max_length=200, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.salary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_title', models.CharField(max_length=1000)),
                ('time_guarantee', models.BigIntegerField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(blank=True, null=True, to='API.comment')),
                ('image', models.ManyToManyField(blank=True, default=None, to='API.image')),
                ('likes_person', models.ManyToManyField(blank=True, null=True, related_name='%(app_label)s_%(class)s_likes_person', to='API.user')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.optionsproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money_bought', models.BigIntegerField(default=0)),
                ('level_customer', models.CharField(choices=[('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold'), ('diamond', 'diamond')], default='bronze', max_length=20)),
                ('product', models.ManyToManyField(to='API.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
                ('product', models.ManyToManyField(to='API.product')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
    ]
