# Generated by Django 4.1.3 on 2022-12-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_time_guarantee',
            field=models.CharField(choices=[('years', 'years'), ('months', 'months')], default='years', max_length=6),
        ),
    ]
