# Generated by Django 4.1.3 on 2022-12-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsproduct',
            name='detail',
            field=models.ManyToManyField(default=None, to='API.detailproduct'),
        ),
    ]
