# Generated by Django 4.1.3 on 2022-12-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_optionsproduct_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.optionsproduct'),
        ),
    ]
