# Generated by Django 4.1.3 on 2022-12-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_product_options_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
