# Generated by Django 4.1.3 on 2022-12-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
