# Generated by Django 4.1.3 on 2023-01-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
