# Generated by Django 4.1.3 on 2023-01-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_optionsproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageID',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
