# Generated by Django 4.1.3 on 2023-02-13 03:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_image_imageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='houseNumber',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=10)),
                ('payment_amount', models.BigIntegerField()),
                ('payment_currency', models.CharField(choices=[('VND', 'VND'), ('USD', 'USD')], default='VND', max_length=5)),
                ('payment_date', models.DateTimeField()),
                ('credit_card_number', models.CharField(max_length=19)),
                ('bank_name', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.product')),
            ],
        ),
    ]
