# Generated by Django 4.1.3 on 2023-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_remove_user_address_user_district_user_housenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ward',
            field=models.IntegerField(blank=True),
        ),
    ]
